# Generated by Django 2.2 on 2021-02-06 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('schedule', '0004_auto_20210102_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('do_not_remove', models.BooleanField(default=False)),
                ('cores', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1),
                                                                     django.core.validators.MaxValueValidator(100)])),
                ('memory_gb', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1),
                                                                         django.core.validators.MaxValueValidator(
                                                                             1000)])),
                ('partition_size_gb',
                 models.IntegerField(default=10, help_text='Affects only when creating a container',
                                     validators=[django.core.validators.MinValueValidator(1),
                                                 django.core.validators.MaxValueValidator(1000)])),
                ('group',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Group')),
            ],
        ),
    ]
