# Generated by Django 2.2 on 2021-03-21 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='memory_gb',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Memory in GB'),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Container name'),
        ),
        migrations.AlterField(
            model_name='container',
            name='partition_size_gb',
            field=models.IntegerField(default=10, help_text='Affects only when creating a container', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Partition size in GB'),
        ),
    ]
