variables:
  # App settings
  LMS_URL: example.com
  LMS_PASSWORD: admin
  DEPARTMENT: MASS APOCRIF
  FILES_ROOT: /app
  DEBUG: 'no'
  LOCALE: C.UTF-8
  BRAND: Interception Intersception

  # Database settings
  POSTGRES_DB: test_smiap
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_PASSWORD: postgres

  # System environment variables
  LANG: $LOCALE
  LANGUAGE: en_US:en
#  LC_ALL: $LANG

  # Ansible variables
  ANSIBLE_FORKS: 2
  ANSIBLE_PIPELINING: 'True'
  ANSIBLE_STRATEGY: 'free'
  ANSIBLE_HOST_KEY_CHECKING: 'False'

  # Pipenv settings
  PIPENV_SYSTEM: 1

stages:
  - test
  - deploy

test:
  image: registry.gitlab.com/assisken/zhipa
  stage: test
  services:
    - postgres:12.2
  script:
    - make lint
    - make test

deploy:
  image: willhallonline/ansible:alpine
  stage: deploy
  when: on_success
  only:
    - master
  script:
    - cp "$DEPLOY_KEY" id_rsa
    - chmod 600 id_rsa
    - ansible-playbook --syntax-check ansible/playbook.yml -i ansible/hosts
    - ansible-vault decrypt ansible/vault.yml --vault-password-file="$VAULT_PASSWORD"
    - ansible-vault decrypt ansible/group_vars/*.yml --vault-password-file="$VAULT_PASSWORD"
    - ansible-playbook -l all -i ansible/hosts --key-file id_rsa --extra-vars '@ansible/vault.yml' ansible/playbook.yml
