version: '3'
services:
  app:
    container_name: smiap
    image: registry.gitlab.com/assisken/zhipa
    command: make test
    tty: yes
    ports:
      - "8000:8000"
    extra_hosts:
      - "smiap:172.17.0.1"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/tmp/static:/static"
    depends_on:
      - db

  db:
    container_name: pg-smiap
    image: postgres:12.3
    restart: always
    volumes:
      - ~/smiap_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=smiap
      - POSTGRES_DB=smiap
      - POSTGRES_USER=smiap
