version: '3'
services:
  app:
    container_name: smiap-app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      cat < /dev/null > /dev/tcp/db/5432 || sleep 5;
      /app/entrypoint.sh"
    tty: yes
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - SECRET_KEY=in_development...
      - FILES_ROOT=/static
      - POSTGRES_PASSWORD=smiap
      - POSTGRES_DB=smiap
      - POSTGRES_USER=smiap
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    container_name: smiap-postgres
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=smiap
      - POSTGRES_DB=smiap
      - POSTGRES_USER=smiap
