# Generated by Django 2.2 on 2020-06-04 00:14

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import news.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_auto_20200604_0300'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('url', models.CharField(blank=True, default=None, max_length=60, null=True, unique=True)),
                ('cover',
                 models.ImageField(blank=True, default='', max_length=120, upload_to=news.models.get_news_cover_path)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('render_in',
                 models.CharField(choices=[('html', 'html'), ('md', 'markdown')], default='html', max_length=8)),
                ('hidden', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='NewsCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img',
                 models.ImageField(blank=True, default='', max_length=120, upload_to=news.models.get_news_cover_path)),
                ('content', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('color', colorfield.fields.ColorField(default='#0997ef', max_length=18)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.CreateModel(
            name='NewsContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[
                    main.validators.validate_news_content_image_begin_name_with_a_letter])),
                ('img', models.ImageField(blank=True, default='', max_length=120,
                                          upload_to=news.models.get_news_content_image_path)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.News')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AlterField(
            model_name='newscover',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
