# Generated by Django 2.2 on 2021-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='render_in',
            field=models.CharField(choices=[('html', 'html'), ('md', 'markdown')], default='md', max_length=8),
        ),
    ]
