# Generated by Django 2.2 on 2021-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210321_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover',
        ),
        migrations.AddField(
            model_name='newscover',
            name='show_content',
            field=models.BooleanField(default=True),
        ),
    ]
