# Generated by Django 2.2 on 2021-03-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210322_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='render_in',
        ),
    ]
