# Generated by Django 2.2 on 2019-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='study_form',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
