# Generated by Django 2.2 on 2019-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190625_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
