# Generated by Django 2.2 on 2019-09-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190907_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Staff'),
        ),
    ]
