# Generated by Django 2.2 on 2019-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='degree',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
