# Generated by Django 2.2 on 2019-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
