# Generated by Django 3.2.1 on 2021-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210505_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
