# Generated by Django 2.2 on 2019-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_schedule_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='group',
        ),
        migrations.AddField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
