# Generated by Django 2.2 on 2019-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='study_form',
            field=models.CharField(choices=[('очная', 'очная'), ('очно-заочная', 'очно-заочная'), ('заочная', 'заочная')], max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР')], max_length=3),
        ),
    ]
