# Generated by Django 2.2 on 2019-10-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='week_day',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_form',
            field=models.CharField(choices=[('очная', 'очная'), ('очно-заочная', 'очно-заочная'), ('заочная', 'заочная')], max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР')], max_length=3),
        ),
    ]
