# Generated by Django 2.2 on 2019-10-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190930_1312'),
        ('main', '0007_auto_20191001_1644'),
    ]

    operations = [
    ]
