# Generated by Django 2.2 on 2019-10-13 16:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Schedule',
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='', max_length=120, upload_to=main.models.get_news_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default=None, max_length=60, null=True, upload_to=main.models.get_profile_image_path),
        ),
    ]
