# Generated by Django 2.2 on 2019-10-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191013_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('month', 'day')},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Schedule'},
        ),
        migrations.CreateModel(
            name='ExtramuralSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField()),
                ('times', models.TextField()),
                ('item', models.TextField()),
                ('teachers', models.TextField()),
                ('places', models.TextField()),
                ('group', models.ManyToManyField(to='main.Group')),
            ],
            options={
                'verbose_name_plural': 'Extramural Schedule',
            },
        ),
    ]
