# Generated by Django 2.2 on 2019-10-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191014_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extramuralschedule',
            old_name='group',
            new_name='groups',
        ),
    ]
