# Generated by Django 2.2 on 2019-10-18 21:10

from django.db import migrations, models
import django.db.models.deletion
import main.models
from news.models import get_news_content_image_path


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191014_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='img',
            new_name='cover',
        ),
        migrations.CreateModel(
            name='NewsContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(blank=True, default='', max_length=120, upload_to=get_news_content_image_path)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.News')),
            ],
        ),
    ]
