# Generated by Django 2.2 on 2019-10-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191019_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='render_in',
            field=models.CharField(choices=[('html', 'html'), ('md', 'markdown')], default='html', max_length=8),
        ),
        migrations.AlterField(
            model_name='newscontentimage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
