# Generated by Django 2.2 on 2019-10-28 21:43

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191026_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontentimage',
            name='name',
            field=models.CharField(max_length=200, validators=[main.validators.validate_news_content_image_begin_name_with_a_letter]),
        ),
    ]
