# Generated by Django 2.2 on 2019-12-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191029_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTimeSchedule',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Fulltime Schedule',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.schedule',),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('degree', 'course', '-study_form', 'name')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('building', 'number', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-leader', 'lecturer', 'hide', 'lastname', 'firstname', 'middlename', 'pk'), 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='item_type',
            field=models.CharField(choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР'), ('Экз', 'Экзамен'), ('', 'Оставить пустым')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('Учебн.', 'Учебное время'), ('Сессия', 'Сессия')], default='Учебн.', max_length=6),
        ),
        migrations.AlterField(
            model_name='day',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExtramuralSchedule',
        ),
        migrations.CreateModel(
            name='ExtramuralSchedule',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Extramural Schedule',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.fulltimeschedule',),
        ),
    ]
