# Generated by Django 2.2 on 2020-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191229_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('lastname', 'firstname', 'middlename')},
        ),
        migrations.AlterField(
            model_name='day',
            name='week_day',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='item_type',
            field=models.CharField(blank=True, choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР'), ('Экз', 'Экзамен'), ('', 'Оставить пустым')], default='', max_length=3),
        ),
    ]
