# Generated by Django 2.2 on 2020-02-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200118_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtramuralSchedule',
        ),
        migrations.DeleteModel(
            name='FullTimeSchedule',
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-leader', '-lecturer', 'hide', 'lastname', 'firstname', 'middlename', 'pk'), 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='groups',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtramuralSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Schedule')),
            ],
            options={
                'verbose_name_plural': 'Extramural Schedule',
            },
            bases=('main.schedule',),
        ),
        migrations.CreateModel(
            name='FullTimeSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Schedule')),
            ],
            options={
                'verbose_name_plural': 'Extramural Schedule',
            },
            bases=('main.schedule',),
        ),
    ]
