# Generated by Django 2.2 on 2020-02-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200214_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulltimeschedule',
            options={'verbose_name_plural': 'Fulltime Schedule'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='extramuralschedule',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extramuralschedule',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulltimeschedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Day'),
        ),
        migrations.AddField(
            model_name='fulltimeschedule',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulltimeschedule',
            name='item_type',
            field=models.CharField(blank=True, choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР'), ('Экз', 'Экзамен'), ('', 'Оставить пустым')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='fulltimeschedule',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('Учебн.', 'Учебное время'), ('Сессия', 'Сессия')], default='Учебн.', max_length=6, null=True),
        ),
    ]
