# Generated by Django 2.2 on 2020-05-21 11:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200224_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-pk',)},
        ),
        migrations.CreateModel(
            name='NewsCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', max_length=120, upload_to=main.models.get_news_cover_path)),
                ('content', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('color', colorfield.fields.ColorField(default='#0997ef', max_length=18)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News')),
            ],
        ),
    ]
