# Generated by Django 2.2 on 2020-05-23 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='link',
            field=models.CharField(default='c5ceb90a', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 2, 29, 2, 527614)),
        ),
    ]
