# Generated by Django 2.2 on 2020-06-04 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_auto_20200524_0229'),
    ]

    database_operations = [
        migrations.AlterModelTable('News', 'news_news'),
        migrations.AlterModelTable('NewsContentImage', 'news_newscontentimage'),
        migrations.AlterModelTable('NewsCover', 'news_newscover')
    ]

    state_operations = [
        migrations.DeleteModel('News'),
        migrations.DeleteModel('NewsContentImage'),
        migrations.DeleteModel('NewsCover'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
