# Generated by Django 2.2 on 2020-06-06 12:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0023_auto_20200604_0300'),
    ]

    database_operations = [
        migrations.AlterModelTable('Group', 'schedule_group'),
        migrations.AlterModelTable('Teacher', 'schedule_teacher'),
        migrations.AlterModelTable('Place', 'schedule_place'),
        migrations.AlterModelTable('Day', 'schedule_day'),
        migrations.AlterModelTable('Schedule', 'schedule_schedule'),
        migrations.AlterModelTable('FullTimeSchedule', 'schedule_fulltimeschedule'),
        migrations.AlterModelTable('ExtramuralSchedule', 'schedule_extramuralschedule'),
    ]

    state_operations = [
        migrations.DeleteModel('Group'),
        migrations.DeleteModel('Teacher'),
        migrations.DeleteModel('Place'),
        migrations.DeleteModel('Day'),
        migrations.DeleteModel('Schedule'),
        migrations.DeleteModel('FullTimeSchedule'),
        migrations.DeleteModel('ExtramuralSchedule'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations),
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.CharField(default=main.models.get_random_link, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
