# Generated by Django 2.2 on 2020-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0025_auto_20200621_1456'), ('main', '0026_publication_author_profiles'), ('main', '0027_auto_20200621_2137'), ('main', '0026_auto_20200621_2210')]

    dependencies = [
        ('main', '0024_auto_20200606_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='closed',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы открыть профиль',
                                      verbose_name='Закрытый профиль'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author_profiles',
            field=models.ManyToManyField(blank=True, help_text='При создании новой публикации заполняется автоматически.', to='main.Profile'),
        ),
    ]
