# Generated by Django 2.2 on 2020-07-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('week_day', models.CharField(blank=True, max_length=2)),
                ('week', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('month', 'day'),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('course', models.PositiveSmallIntegerField(editable=False)),
                ('degree', models.PositiveSmallIntegerField(editable=False)),
                ('semester', models.PositiveSmallIntegerField()),
                ('study_form', models.CharField(choices=[('очная', 'очная'), ('очно-заочная', 'очно-заочная'), ('заочная', 'заочная')], max_length=12)),
                ('schedule_version', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('degree', 'course', '-study_form', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField()),
                ('number', models.TextField(null=True)),
            ],
            options={
                'ordering': ('building', 'number', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('Учебн.', 'Учебное время'), ('Сессия', 'Сессия')], default='Учебн.', max_length=6, null=True)),
                ('name', models.TextField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Group')),
                ('places', models.ManyToManyField(to='schedule.Place')),
            ],
        ),
        migrations.CreateModel(
            name='ExtramuralSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Schedule')),
                ('day', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Extramural Schedule',
            },
            bases=('schedule.schedule',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Staff')),
            ],
            options={
                'ordering': ('lastname', 'firstname', 'middlename'),
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='teachers',
            field=models.ManyToManyField(to='schedule.Teacher'),
        ),
        migrations.CreateModel(
            name='FullTimeSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Schedule')),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('ЛК', 'ЛК'), ('ПЗ', 'ПЗ'), ('ЛР', 'ЛР'), ('КСР', 'КСР'), ('Экз', 'Экзамен'), ('', 'Оставить пустым')], default='', max_length=3)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Day')),
            ],
            options={
                'verbose_name_plural': 'Fulltime Schedule',
            },
            bases=('schedule.schedule',),
        ),
    ]
