# Generated by Django 2.2 on 2020-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
    ]
