# Generated by Django 2.2 on 2020-09-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_schedule_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulltimeschedule",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ЛК", "ЛК"),
                    ("ПЗ", "ПЗ"),
                    ("ЛР", "ЛР"),
                    ("КСР", "КСР"),
                    ("Экз", "Экзамен"),
                    ("ПЗ ЛК", "ПЗ и ЛК"),
                    ("", "Оставить пустым"),
                ],
                default="",
                max_length=5,
            ),
        ),
    ]
