# Generated by Django 2.2 on 2021-01-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_auto_20200914_2227"),
    ]

    operations = [
        migrations.RemoveField(model_name="extramuralschedule", name="day",),
        migrations.RemoveField(model_name="extramuralschedule", name="time",),
        migrations.RemoveField(model_name="fulltimeschedule", name="day",),
        migrations.RemoveField(model_name="fulltimeschedule", name="ends_at",),
        migrations.RemoveField(model_name="fulltimeschedule", name="starts_at",),
        migrations.RemoveField(model_name="group", name="schedule_version",),
        migrations.RemoveField(model_name="schedule", name="places",),
        migrations.AddField(
            model_name="fulltimeschedule",
            name="week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fulltimeschedule",
            name="week_day",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="date",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="schedule", name="place", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="time",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="fulltimeschedule",
            name="item_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="staff",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.Staff"
            ),
        ),
        migrations.DeleteModel(name="Day",),
        migrations.DeleteModel(name="Place",),
    ]
