name: Test and Push the Docker image

on:
  pull_request:
    types:
      - closed
    branches:
      - $default-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=docker.pkg.github.com/${{ github.repository }}/zhipa:${{ github.sha }}
          tags: docker.pkg.github.com/${{ github.repository }}/zhipa:latest
          pull: yes
          push: yes
