name: Test and Push the Docker image

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ github.sha }}
          tags: ghcr.io/${{ github.repository }}:latest
          pull: true
          push: true

      - name: Trigger repo dispatch
        run: |
          curl \
            --request POST \
            --user    "${{ secrets.CR_PAT }}" \
            --header  "Accept: application/vnd.github.everest-preview+json" \
            --header  "Content-Type: application/json" \
            --data    '{"event_type": "${{ secrets.EVENT_TYPE }}"}'
            https://api.github.com/repos/${{ secrets.TARGET_REPOSITORY }}/dispatches
