name: Test the project

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build packages
        run: sudo apt-get install -y locales libsass-dev libc-bin libjpeg-dev libxslt1-dev libpq-dev gcc g++ linux-headers-$(uname -r) postgresql

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev

      - name: Lint code
        run: make lint

      - name: Run test
        run: make test
