name: Test the project

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/zhipa
          tags: ${{ github.sha }}
          push: no
          pull: yes

      - name: Run lint
        run: docker run -e ENV=testing docker.pkg.github.com/$GITHUB_REPOSITORY/zhipa:$GITHUB_SHA make lint

      - name: Run test
        run: docker run -e ENV=testing docker.pkg.github.com/$GITHUB_REPOSITORY/zhipa:$GITHUB_SHA make test
